/*
 * Generated by gdbus-codegen 2.49.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __SRC_SHELL_DBUS_H__
#define __SRC_SHELL_DBUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.gnome.Shell.Screenshot */

#define TYPE_ORG_GNOME_SHELL_SCREENSHOT (org_gnome_shell_screenshot_get_type ())
#define ORG_GNOME_SHELL_SCREENSHOT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT, OrgGnomeShellScreenshot))
#define IS_ORG_GNOME_SHELL_SCREENSHOT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT))
#define ORG_GNOME_SHELL_SCREENSHOT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT, OrgGnomeShellScreenshotIface))

struct _OrgGnomeShellScreenshot;
typedef struct _OrgGnomeShellScreenshot OrgGnomeShellScreenshot;
typedef struct _OrgGnomeShellScreenshotIface OrgGnomeShellScreenshotIface;

struct _OrgGnomeShellScreenshotIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_flash_area) (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation,
    gint arg_x,
    gint arg_y,
    gint arg_width,
    gint arg_height);

  gboolean (*handle_screenshot) (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation,
    gboolean arg_include_cursor,
    gboolean arg_flash,
    const gchar *arg_filename);

  gboolean (*handle_screenshot_area) (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation,
    gint arg_x,
    gint arg_y,
    gint arg_width,
    gint arg_height,
    gboolean arg_flash,
    const gchar *arg_filename);

  gboolean (*handle_screenshot_window) (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation,
    gboolean arg_include_frame,
    gboolean arg_include_cursor,
    gboolean arg_flash,
    const gchar *arg_filename);

  gboolean (*handle_select_area) (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation);

};

GType org_gnome_shell_screenshot_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_gnome_shell_screenshot_interface_info (void);
guint org_gnome_shell_screenshot_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_gnome_shell_screenshot_complete_screenshot (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation,
    gboolean success,
    const gchar *filename_used);

void org_gnome_shell_screenshot_complete_screenshot_window (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation,
    gboolean success,
    const gchar *filename_used);

void org_gnome_shell_screenshot_complete_screenshot_area (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation,
    gboolean success,
    const gchar *filename_used);

void org_gnome_shell_screenshot_complete_flash_area (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation);

void org_gnome_shell_screenshot_complete_select_area (
    OrgGnomeShellScreenshot *object,
    GDBusMethodInvocation *invocation,
    gint x,
    gint y,
    gint width,
    gint height);



/* D-Bus method calls: */
void org_gnome_shell_screenshot_call_screenshot (
    OrgGnomeShellScreenshot *proxy,
    gboolean arg_include_cursor,
    gboolean arg_flash,
    const gchar *arg_filename,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_shell_screenshot_call_screenshot_finish (
    OrgGnomeShellScreenshot *proxy,
    gboolean *out_success,
    gchar **out_filename_used,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_shell_screenshot_call_screenshot_sync (
    OrgGnomeShellScreenshot *proxy,
    gboolean arg_include_cursor,
    gboolean arg_flash,
    const gchar *arg_filename,
    gboolean *out_success,
    gchar **out_filename_used,
    GCancellable *cancellable,
    GError **error);

void org_gnome_shell_screenshot_call_screenshot_window (
    OrgGnomeShellScreenshot *proxy,
    gboolean arg_include_frame,
    gboolean arg_include_cursor,
    gboolean arg_flash,
    const gchar *arg_filename,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_shell_screenshot_call_screenshot_window_finish (
    OrgGnomeShellScreenshot *proxy,
    gboolean *out_success,
    gchar **out_filename_used,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_shell_screenshot_call_screenshot_window_sync (
    OrgGnomeShellScreenshot *proxy,
    gboolean arg_include_frame,
    gboolean arg_include_cursor,
    gboolean arg_flash,
    const gchar *arg_filename,
    gboolean *out_success,
    gchar **out_filename_used,
    GCancellable *cancellable,
    GError **error);

void org_gnome_shell_screenshot_call_screenshot_area (
    OrgGnomeShellScreenshot *proxy,
    gint arg_x,
    gint arg_y,
    gint arg_width,
    gint arg_height,
    gboolean arg_flash,
    const gchar *arg_filename,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_shell_screenshot_call_screenshot_area_finish (
    OrgGnomeShellScreenshot *proxy,
    gboolean *out_success,
    gchar **out_filename_used,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_shell_screenshot_call_screenshot_area_sync (
    OrgGnomeShellScreenshot *proxy,
    gint arg_x,
    gint arg_y,
    gint arg_width,
    gint arg_height,
    gboolean arg_flash,
    const gchar *arg_filename,
    gboolean *out_success,
    gchar **out_filename_used,
    GCancellable *cancellable,
    GError **error);

void org_gnome_shell_screenshot_call_flash_area (
    OrgGnomeShellScreenshot *proxy,
    gint arg_x,
    gint arg_y,
    gint arg_width,
    gint arg_height,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_shell_screenshot_call_flash_area_finish (
    OrgGnomeShellScreenshot *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_shell_screenshot_call_flash_area_sync (
    OrgGnomeShellScreenshot *proxy,
    gint arg_x,
    gint arg_y,
    gint arg_width,
    gint arg_height,
    GCancellable *cancellable,
    GError **error);

void org_gnome_shell_screenshot_call_select_area (
    OrgGnomeShellScreenshot *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_shell_screenshot_call_select_area_finish (
    OrgGnomeShellScreenshot *proxy,
    gint *out_x,
    gint *out_y,
    gint *out_width,
    gint *out_height,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_shell_screenshot_call_select_area_sync (
    OrgGnomeShellScreenshot *proxy,
    gint *out_x,
    gint *out_y,
    gint *out_width,
    gint *out_height,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_GNOME_SHELL_SCREENSHOT_PROXY (org_gnome_shell_screenshot_proxy_get_type ())
#define ORG_GNOME_SHELL_SCREENSHOT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT_PROXY, OrgGnomeShellScreenshotProxy))
#define ORG_GNOME_SHELL_SCREENSHOT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GNOME_SHELL_SCREENSHOT_PROXY, OrgGnomeShellScreenshotProxyClass))
#define ORG_GNOME_SHELL_SCREENSHOT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT_PROXY, OrgGnomeShellScreenshotProxyClass))
#define IS_ORG_GNOME_SHELL_SCREENSHOT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT_PROXY))
#define IS_ORG_GNOME_SHELL_SCREENSHOT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GNOME_SHELL_SCREENSHOT_PROXY))

typedef struct _OrgGnomeShellScreenshotProxy OrgGnomeShellScreenshotProxy;
typedef struct _OrgGnomeShellScreenshotProxyClass OrgGnomeShellScreenshotProxyClass;
typedef struct _OrgGnomeShellScreenshotProxyPrivate OrgGnomeShellScreenshotProxyPrivate;

struct _OrgGnomeShellScreenshotProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgGnomeShellScreenshotProxyPrivate *priv;
};

struct _OrgGnomeShellScreenshotProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_gnome_shell_screenshot_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeShellScreenshotProxy, g_object_unref)
#endif

void org_gnome_shell_screenshot_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGnomeShellScreenshot *org_gnome_shell_screenshot_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGnomeShellScreenshot *org_gnome_shell_screenshot_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_gnome_shell_screenshot_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGnomeShellScreenshot *org_gnome_shell_screenshot_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGnomeShellScreenshot *org_gnome_shell_screenshot_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_GNOME_SHELL_SCREENSHOT_SKELETON (org_gnome_shell_screenshot_skeleton_get_type ())
#define ORG_GNOME_SHELL_SCREENSHOT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT_SKELETON, OrgGnomeShellScreenshotSkeleton))
#define ORG_GNOME_SHELL_SCREENSHOT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GNOME_SHELL_SCREENSHOT_SKELETON, OrgGnomeShellScreenshotSkeletonClass))
#define ORG_GNOME_SHELL_SCREENSHOT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT_SKELETON, OrgGnomeShellScreenshotSkeletonClass))
#define IS_ORG_GNOME_SHELL_SCREENSHOT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_SHELL_SCREENSHOT_SKELETON))
#define IS_ORG_GNOME_SHELL_SCREENSHOT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GNOME_SHELL_SCREENSHOT_SKELETON))

typedef struct _OrgGnomeShellScreenshotSkeleton OrgGnomeShellScreenshotSkeleton;
typedef struct _OrgGnomeShellScreenshotSkeletonClass OrgGnomeShellScreenshotSkeletonClass;
typedef struct _OrgGnomeShellScreenshotSkeletonPrivate OrgGnomeShellScreenshotSkeletonPrivate;

struct _OrgGnomeShellScreenshotSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgGnomeShellScreenshotSkeletonPrivate *priv;
};

struct _OrgGnomeShellScreenshotSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_gnome_shell_screenshot_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeShellScreenshotSkeleton, g_object_unref)
#endif

OrgGnomeShellScreenshot *org_gnome_shell_screenshot_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.gtk.Notifications */

#define TYPE_ORG_GTK_NOTIFICATIONS (org_gtk_notifications_get_type ())
#define ORG_GTK_NOTIFICATIONS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GTK_NOTIFICATIONS, OrgGtkNotifications))
#define IS_ORG_GTK_NOTIFICATIONS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GTK_NOTIFICATIONS))
#define ORG_GTK_NOTIFICATIONS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_GTK_NOTIFICATIONS, OrgGtkNotificationsIface))

struct _OrgGtkNotifications;
typedef struct _OrgGtkNotifications OrgGtkNotifications;
typedef struct _OrgGtkNotificationsIface OrgGtkNotificationsIface;

struct _OrgGtkNotificationsIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_add_notification) (
    OrgGtkNotifications *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_app_id,
    const gchar *arg_id,
    GVariant *arg_notification);

  gboolean (*handle_remove_notification) (
    OrgGtkNotifications *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_app_id,
    const gchar *arg_id);

};

GType org_gtk_notifications_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_gtk_notifications_interface_info (void);
guint org_gtk_notifications_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_gtk_notifications_complete_add_notification (
    OrgGtkNotifications *object,
    GDBusMethodInvocation *invocation);

void org_gtk_notifications_complete_remove_notification (
    OrgGtkNotifications *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void org_gtk_notifications_call_add_notification (
    OrgGtkNotifications *proxy,
    const gchar *arg_app_id,
    const gchar *arg_id,
    GVariant *arg_notification,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gtk_notifications_call_add_notification_finish (
    OrgGtkNotifications *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gtk_notifications_call_add_notification_sync (
    OrgGtkNotifications *proxy,
    const gchar *arg_app_id,
    const gchar *arg_id,
    GVariant *arg_notification,
    GCancellable *cancellable,
    GError **error);

void org_gtk_notifications_call_remove_notification (
    OrgGtkNotifications *proxy,
    const gchar *arg_app_id,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gtk_notifications_call_remove_notification_finish (
    OrgGtkNotifications *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gtk_notifications_call_remove_notification_sync (
    OrgGtkNotifications *proxy,
    const gchar *arg_app_id,
    const gchar *arg_id,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_GTK_NOTIFICATIONS_PROXY (org_gtk_notifications_proxy_get_type ())
#define ORG_GTK_NOTIFICATIONS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GTK_NOTIFICATIONS_PROXY, OrgGtkNotificationsProxy))
#define ORG_GTK_NOTIFICATIONS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GTK_NOTIFICATIONS_PROXY, OrgGtkNotificationsProxyClass))
#define ORG_GTK_NOTIFICATIONS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GTK_NOTIFICATIONS_PROXY, OrgGtkNotificationsProxyClass))
#define IS_ORG_GTK_NOTIFICATIONS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GTK_NOTIFICATIONS_PROXY))
#define IS_ORG_GTK_NOTIFICATIONS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GTK_NOTIFICATIONS_PROXY))

typedef struct _OrgGtkNotificationsProxy OrgGtkNotificationsProxy;
typedef struct _OrgGtkNotificationsProxyClass OrgGtkNotificationsProxyClass;
typedef struct _OrgGtkNotificationsProxyPrivate OrgGtkNotificationsProxyPrivate;

struct _OrgGtkNotificationsProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgGtkNotificationsProxyPrivate *priv;
};

struct _OrgGtkNotificationsProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_gtk_notifications_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGtkNotificationsProxy, g_object_unref)
#endif

void org_gtk_notifications_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGtkNotifications *org_gtk_notifications_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGtkNotifications *org_gtk_notifications_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_gtk_notifications_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGtkNotifications *org_gtk_notifications_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGtkNotifications *org_gtk_notifications_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_GTK_NOTIFICATIONS_SKELETON (org_gtk_notifications_skeleton_get_type ())
#define ORG_GTK_NOTIFICATIONS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GTK_NOTIFICATIONS_SKELETON, OrgGtkNotificationsSkeleton))
#define ORG_GTK_NOTIFICATIONS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GTK_NOTIFICATIONS_SKELETON, OrgGtkNotificationsSkeletonClass))
#define ORG_GTK_NOTIFICATIONS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GTK_NOTIFICATIONS_SKELETON, OrgGtkNotificationsSkeletonClass))
#define IS_ORG_GTK_NOTIFICATIONS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GTK_NOTIFICATIONS_SKELETON))
#define IS_ORG_GTK_NOTIFICATIONS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GTK_NOTIFICATIONS_SKELETON))

typedef struct _OrgGtkNotificationsSkeleton OrgGtkNotificationsSkeleton;
typedef struct _OrgGtkNotificationsSkeletonClass OrgGtkNotificationsSkeletonClass;
typedef struct _OrgGtkNotificationsSkeletonPrivate OrgGtkNotificationsSkeletonPrivate;

struct _OrgGtkNotificationsSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgGtkNotificationsSkeletonPrivate *priv;
};

struct _OrgGtkNotificationsSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_gtk_notifications_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGtkNotificationsSkeleton, g_object_unref)
#endif

OrgGtkNotifications *org_gtk_notifications_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.gnome.SessionManager */

#define TYPE_ORG_GNOME_SESSION_MANAGER (org_gnome_session_manager_get_type ())
#define ORG_GNOME_SESSION_MANAGER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_SESSION_MANAGER, OrgGnomeSessionManager))
#define IS_ORG_GNOME_SESSION_MANAGER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_SESSION_MANAGER))
#define ORG_GNOME_SESSION_MANAGER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_GNOME_SESSION_MANAGER, OrgGnomeSessionManagerIface))

struct _OrgGnomeSessionManager;
typedef struct _OrgGnomeSessionManager OrgGnomeSessionManager;
typedef struct _OrgGnomeSessionManagerIface OrgGnomeSessionManagerIface;

struct _OrgGnomeSessionManagerIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_can_shutdown) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_clients) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_inhibitors) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_locale) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    gint arg_category);

  gboolean (*handle_inhibit) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_app_id,
    guint arg_toplevel_xid,
    const gchar *arg_reason,
    guint arg_flags);

  gboolean (*handle_initialization_error) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_message,
    gboolean arg_fatal);

  gboolean (*handle_is_autostart_condition_handled) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_condition);

  gboolean (*handle_is_inhibited) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    guint arg_flags);

  gboolean (*handle_is_session_running) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_logout) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    guint arg_mode);

  gboolean (*handle_reboot) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_register_client) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_app_id,
    const gchar *arg_client_startup_id);

  gboolean (*handle_setenv) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_variable,
    const gchar *arg_value);

  gboolean (*handle_shutdown) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_uninhibit) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    guint arg_inhibit_cookie);

  gboolean (*handle_unregister_client) (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_client_id);

  guint  (*get_inhibited_actions) (OrgGnomeSessionManager *object);

  gboolean  (*get_session_is_active) (OrgGnomeSessionManager *object);

  const gchar * (*get_session_name) (OrgGnomeSessionManager *object);

  void (*client_added) (
    OrgGnomeSessionManager *object,
    const gchar *arg_id);

  void (*client_removed) (
    OrgGnomeSessionManager *object,
    const gchar *arg_id);

  void (*inhibitor_added) (
    OrgGnomeSessionManager *object,
    const gchar *arg_id);

  void (*inhibitor_removed) (
    OrgGnomeSessionManager *object,
    const gchar *arg_id);

  void (*session_over) (
    OrgGnomeSessionManager *object);

  void (*session_running) (
    OrgGnomeSessionManager *object);

};

GType org_gnome_session_manager_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_gnome_session_manager_interface_info (void);
guint org_gnome_session_manager_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_gnome_session_manager_complete_setenv (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

void org_gnome_session_manager_complete_get_locale (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *value);

void org_gnome_session_manager_complete_initialization_error (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

void org_gnome_session_manager_complete_register_client (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *client_id);

void org_gnome_session_manager_complete_unregister_client (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

void org_gnome_session_manager_complete_inhibit (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    guint inhibit_cookie);

void org_gnome_session_manager_complete_uninhibit (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

void org_gnome_session_manager_complete_is_inhibited (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    gboolean is_inhibited);

void org_gnome_session_manager_complete_get_clients (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *clients);

void org_gnome_session_manager_complete_get_inhibitors (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *inhibitors);

void org_gnome_session_manager_complete_is_autostart_condition_handled (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    gboolean handled);

void org_gnome_session_manager_complete_shutdown (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

void org_gnome_session_manager_complete_reboot (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

void org_gnome_session_manager_complete_can_shutdown (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    gboolean is_available);

void org_gnome_session_manager_complete_logout (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation);

void org_gnome_session_manager_complete_is_session_running (
    OrgGnomeSessionManager *object,
    GDBusMethodInvocation *invocation,
    gboolean running);



/* D-Bus signal emissions functions: */
void org_gnome_session_manager_emit_client_added (
    OrgGnomeSessionManager *object,
    const gchar *arg_id);

void org_gnome_session_manager_emit_client_removed (
    OrgGnomeSessionManager *object,
    const gchar *arg_id);

void org_gnome_session_manager_emit_inhibitor_added (
    OrgGnomeSessionManager *object,
    const gchar *arg_id);

void org_gnome_session_manager_emit_inhibitor_removed (
    OrgGnomeSessionManager *object,
    const gchar *arg_id);

void org_gnome_session_manager_emit_session_running (
    OrgGnomeSessionManager *object);

void org_gnome_session_manager_emit_session_over (
    OrgGnomeSessionManager *object);



/* D-Bus method calls: */
void org_gnome_session_manager_call_setenv (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_variable,
    const gchar *arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_setenv_finish (
    OrgGnomeSessionManager *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_setenv_sync (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_variable,
    const gchar *arg_value,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_get_locale (
    OrgGnomeSessionManager *proxy,
    gint arg_category,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_get_locale_finish (
    OrgGnomeSessionManager *proxy,
    gchar **out_value,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_get_locale_sync (
    OrgGnomeSessionManager *proxy,
    gint arg_category,
    gchar **out_value,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_initialization_error (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_message,
    gboolean arg_fatal,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_initialization_error_finish (
    OrgGnomeSessionManager *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_initialization_error_sync (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_message,
    gboolean arg_fatal,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_register_client (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_app_id,
    const gchar *arg_client_startup_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_register_client_finish (
    OrgGnomeSessionManager *proxy,
    gchar **out_client_id,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_register_client_sync (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_app_id,
    const gchar *arg_client_startup_id,
    gchar **out_client_id,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_unregister_client (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_client_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_unregister_client_finish (
    OrgGnomeSessionManager *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_unregister_client_sync (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_client_id,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_inhibit (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_app_id,
    guint arg_toplevel_xid,
    const gchar *arg_reason,
    guint arg_flags,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_inhibit_finish (
    OrgGnomeSessionManager *proxy,
    guint *out_inhibit_cookie,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_inhibit_sync (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_app_id,
    guint arg_toplevel_xid,
    const gchar *arg_reason,
    guint arg_flags,
    guint *out_inhibit_cookie,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_uninhibit (
    OrgGnomeSessionManager *proxy,
    guint arg_inhibit_cookie,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_uninhibit_finish (
    OrgGnomeSessionManager *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_uninhibit_sync (
    OrgGnomeSessionManager *proxy,
    guint arg_inhibit_cookie,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_is_inhibited (
    OrgGnomeSessionManager *proxy,
    guint arg_flags,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_is_inhibited_finish (
    OrgGnomeSessionManager *proxy,
    gboolean *out_is_inhibited,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_is_inhibited_sync (
    OrgGnomeSessionManager *proxy,
    guint arg_flags,
    gboolean *out_is_inhibited,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_get_clients (
    OrgGnomeSessionManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_get_clients_finish (
    OrgGnomeSessionManager *proxy,
    gchar ***out_clients,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_get_clients_sync (
    OrgGnomeSessionManager *proxy,
    gchar ***out_clients,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_get_inhibitors (
    OrgGnomeSessionManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_get_inhibitors_finish (
    OrgGnomeSessionManager *proxy,
    gchar ***out_inhibitors,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_get_inhibitors_sync (
    OrgGnomeSessionManager *proxy,
    gchar ***out_inhibitors,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_is_autostart_condition_handled (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_condition,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_is_autostart_condition_handled_finish (
    OrgGnomeSessionManager *proxy,
    gboolean *out_handled,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_is_autostart_condition_handled_sync (
    OrgGnomeSessionManager *proxy,
    const gchar *arg_condition,
    gboolean *out_handled,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_shutdown (
    OrgGnomeSessionManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_shutdown_finish (
    OrgGnomeSessionManager *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_shutdown_sync (
    OrgGnomeSessionManager *proxy,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_reboot (
    OrgGnomeSessionManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_reboot_finish (
    OrgGnomeSessionManager *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_reboot_sync (
    OrgGnomeSessionManager *proxy,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_can_shutdown (
    OrgGnomeSessionManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_can_shutdown_finish (
    OrgGnomeSessionManager *proxy,
    gboolean *out_is_available,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_can_shutdown_sync (
    OrgGnomeSessionManager *proxy,
    gboolean *out_is_available,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_logout (
    OrgGnomeSessionManager *proxy,
    guint arg_mode,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_logout_finish (
    OrgGnomeSessionManager *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_logout_sync (
    OrgGnomeSessionManager *proxy,
    guint arg_mode,
    GCancellable *cancellable,
    GError **error);

void org_gnome_session_manager_call_is_session_running (
    OrgGnomeSessionManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_session_manager_call_is_session_running_finish (
    OrgGnomeSessionManager *proxy,
    gboolean *out_running,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_session_manager_call_is_session_running_sync (
    OrgGnomeSessionManager *proxy,
    gboolean *out_running,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *org_gnome_session_manager_get_session_name (OrgGnomeSessionManager *object);
gchar *org_gnome_session_manager_dup_session_name (OrgGnomeSessionManager *object);
void org_gnome_session_manager_set_session_name (OrgGnomeSessionManager *object, const gchar *value);

gboolean org_gnome_session_manager_get_session_is_active (OrgGnomeSessionManager *object);
void org_gnome_session_manager_set_session_is_active (OrgGnomeSessionManager *object, gboolean value);

guint org_gnome_session_manager_get_inhibited_actions (OrgGnomeSessionManager *object);
void org_gnome_session_manager_set_inhibited_actions (OrgGnomeSessionManager *object, guint value);


/* ---- */

#define TYPE_ORG_GNOME_SESSION_MANAGER_PROXY (org_gnome_session_manager_proxy_get_type ())
#define ORG_GNOME_SESSION_MANAGER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_SESSION_MANAGER_PROXY, OrgGnomeSessionManagerProxy))
#define ORG_GNOME_SESSION_MANAGER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GNOME_SESSION_MANAGER_PROXY, OrgGnomeSessionManagerProxyClass))
#define ORG_GNOME_SESSION_MANAGER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GNOME_SESSION_MANAGER_PROXY, OrgGnomeSessionManagerProxyClass))
#define IS_ORG_GNOME_SESSION_MANAGER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_SESSION_MANAGER_PROXY))
#define IS_ORG_GNOME_SESSION_MANAGER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GNOME_SESSION_MANAGER_PROXY))

typedef struct _OrgGnomeSessionManagerProxy OrgGnomeSessionManagerProxy;
typedef struct _OrgGnomeSessionManagerProxyClass OrgGnomeSessionManagerProxyClass;
typedef struct _OrgGnomeSessionManagerProxyPrivate OrgGnomeSessionManagerProxyPrivate;

struct _OrgGnomeSessionManagerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgGnomeSessionManagerProxyPrivate *priv;
};

struct _OrgGnomeSessionManagerProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_gnome_session_manager_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeSessionManagerProxy, g_object_unref)
#endif

void org_gnome_session_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGnomeSessionManager *org_gnome_session_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGnomeSessionManager *org_gnome_session_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_gnome_session_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGnomeSessionManager *org_gnome_session_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGnomeSessionManager *org_gnome_session_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_GNOME_SESSION_MANAGER_SKELETON (org_gnome_session_manager_skeleton_get_type ())
#define ORG_GNOME_SESSION_MANAGER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_SESSION_MANAGER_SKELETON, OrgGnomeSessionManagerSkeleton))
#define ORG_GNOME_SESSION_MANAGER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GNOME_SESSION_MANAGER_SKELETON, OrgGnomeSessionManagerSkeletonClass))
#define ORG_GNOME_SESSION_MANAGER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GNOME_SESSION_MANAGER_SKELETON, OrgGnomeSessionManagerSkeletonClass))
#define IS_ORG_GNOME_SESSION_MANAGER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_SESSION_MANAGER_SKELETON))
#define IS_ORG_GNOME_SESSION_MANAGER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GNOME_SESSION_MANAGER_SKELETON))

typedef struct _OrgGnomeSessionManagerSkeleton OrgGnomeSessionManagerSkeleton;
typedef struct _OrgGnomeSessionManagerSkeletonClass OrgGnomeSessionManagerSkeletonClass;
typedef struct _OrgGnomeSessionManagerSkeletonPrivate OrgGnomeSessionManagerSkeletonPrivate;

struct _OrgGnomeSessionManagerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgGnomeSessionManagerSkeletonPrivate *priv;
};

struct _OrgGnomeSessionManagerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_gnome_session_manager_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeSessionManagerSkeleton, g_object_unref)
#endif

OrgGnomeSessionManager *org_gnome_session_manager_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.ScreenSaver */

#define TYPE_ORG_FREEDESKTOP_SCREEN_SAVER (org_freedesktop_screen_saver_get_type ())
#define ORG_FREEDESKTOP_SCREEN_SAVER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER, OrgFreedesktopScreenSaver))
#define IS_ORG_FREEDESKTOP_SCREEN_SAVER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER))
#define ORG_FREEDESKTOP_SCREEN_SAVER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER, OrgFreedesktopScreenSaverIface))

struct _OrgFreedesktopScreenSaver;
typedef struct _OrgFreedesktopScreenSaver OrgFreedesktopScreenSaver;
typedef struct _OrgFreedesktopScreenSaverIface OrgFreedesktopScreenSaverIface;

struct _OrgFreedesktopScreenSaverIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_active) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_active_time) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_session_idle_time) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_inhibit) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_application_name,
    const gchar *arg_reason_for_inhibit);

  gboolean (*handle_lock) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_active) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    gboolean arg_e);

  gboolean (*handle_simulate_user_activity) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_throttle) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_application_name,
    const gchar *arg_reason_for_inhibit);

  gboolean (*handle_un_inhibit) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    guint arg_cookie);

  gboolean (*handle_un_throttle) (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    guint arg_cookie);

  void (*active_changed) (
    OrgFreedesktopScreenSaver *object,
    gboolean arg_unnamed_arg0);

};

GType org_freedesktop_screen_saver_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_freedesktop_screen_saver_interface_info (void);
guint org_freedesktop_screen_saver_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_freedesktop_screen_saver_complete_lock (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_screen_saver_complete_simulate_user_activity (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_screen_saver_complete_get_active (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg0);

void org_freedesktop_screen_saver_complete_get_active_time (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    guint seconds);

void org_freedesktop_screen_saver_complete_get_session_idle_time (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    guint seconds);

void org_freedesktop_screen_saver_complete_set_active (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg1);

void org_freedesktop_screen_saver_complete_inhibit (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    guint cookie);

void org_freedesktop_screen_saver_complete_un_inhibit (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);

void org_freedesktop_screen_saver_complete_throttle (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation,
    guint cookie);

void org_freedesktop_screen_saver_complete_un_throttle (
    OrgFreedesktopScreenSaver *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void org_freedesktop_screen_saver_emit_active_changed (
    OrgFreedesktopScreenSaver *object,
    gboolean arg_unnamed_arg0);



/* D-Bus method calls: */
void org_freedesktop_screen_saver_call_lock (
    OrgFreedesktopScreenSaver *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_lock_finish (
    OrgFreedesktopScreenSaver *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_lock_sync (
    OrgFreedesktopScreenSaver *proxy,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_simulate_user_activity (
    OrgFreedesktopScreenSaver *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_simulate_user_activity_finish (
    OrgFreedesktopScreenSaver *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_simulate_user_activity_sync (
    OrgFreedesktopScreenSaver *proxy,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_get_active (
    OrgFreedesktopScreenSaver *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_get_active_finish (
    OrgFreedesktopScreenSaver *proxy,
    gboolean *out_unnamed_arg0,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_get_active_sync (
    OrgFreedesktopScreenSaver *proxy,
    gboolean *out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_get_active_time (
    OrgFreedesktopScreenSaver *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_get_active_time_finish (
    OrgFreedesktopScreenSaver *proxy,
    guint *out_seconds,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_get_active_time_sync (
    OrgFreedesktopScreenSaver *proxy,
    guint *out_seconds,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_get_session_idle_time (
    OrgFreedesktopScreenSaver *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_get_session_idle_time_finish (
    OrgFreedesktopScreenSaver *proxy,
    guint *out_seconds,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_get_session_idle_time_sync (
    OrgFreedesktopScreenSaver *proxy,
    guint *out_seconds,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_set_active (
    OrgFreedesktopScreenSaver *proxy,
    gboolean arg_e,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_set_active_finish (
    OrgFreedesktopScreenSaver *proxy,
    gboolean *out_unnamed_arg1,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_set_active_sync (
    OrgFreedesktopScreenSaver *proxy,
    gboolean arg_e,
    gboolean *out_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_inhibit (
    OrgFreedesktopScreenSaver *proxy,
    const gchar *arg_application_name,
    const gchar *arg_reason_for_inhibit,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_inhibit_finish (
    OrgFreedesktopScreenSaver *proxy,
    guint *out_cookie,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_inhibit_sync (
    OrgFreedesktopScreenSaver *proxy,
    const gchar *arg_application_name,
    const gchar *arg_reason_for_inhibit,
    guint *out_cookie,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_un_inhibit (
    OrgFreedesktopScreenSaver *proxy,
    guint arg_cookie,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_un_inhibit_finish (
    OrgFreedesktopScreenSaver *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_un_inhibit_sync (
    OrgFreedesktopScreenSaver *proxy,
    guint arg_cookie,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_throttle (
    OrgFreedesktopScreenSaver *proxy,
    const gchar *arg_application_name,
    const gchar *arg_reason_for_inhibit,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_throttle_finish (
    OrgFreedesktopScreenSaver *proxy,
    guint *out_cookie,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_throttle_sync (
    OrgFreedesktopScreenSaver *proxy,
    const gchar *arg_application_name,
    const gchar *arg_reason_for_inhibit,
    guint *out_cookie,
    GCancellable *cancellable,
    GError **error);

void org_freedesktop_screen_saver_call_un_throttle (
    OrgFreedesktopScreenSaver *proxy,
    guint arg_cookie,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_freedesktop_screen_saver_call_un_throttle_finish (
    OrgFreedesktopScreenSaver *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_freedesktop_screen_saver_call_un_throttle_sync (
    OrgFreedesktopScreenSaver *proxy,
    guint arg_cookie,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_PROXY (org_freedesktop_screen_saver_proxy_get_type ())
#define ORG_FREEDESKTOP_SCREEN_SAVER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_PROXY, OrgFreedesktopScreenSaverProxy))
#define ORG_FREEDESKTOP_SCREEN_SAVER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_PROXY, OrgFreedesktopScreenSaverProxyClass))
#define ORG_FREEDESKTOP_SCREEN_SAVER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_PROXY, OrgFreedesktopScreenSaverProxyClass))
#define IS_ORG_FREEDESKTOP_SCREEN_SAVER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_PROXY))
#define IS_ORG_FREEDESKTOP_SCREEN_SAVER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_PROXY))

typedef struct _OrgFreedesktopScreenSaverProxy OrgFreedesktopScreenSaverProxy;
typedef struct _OrgFreedesktopScreenSaverProxyClass OrgFreedesktopScreenSaverProxyClass;
typedef struct _OrgFreedesktopScreenSaverProxyPrivate OrgFreedesktopScreenSaverProxyPrivate;

struct _OrgFreedesktopScreenSaverProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgFreedesktopScreenSaverProxyPrivate *priv;
};

struct _OrgFreedesktopScreenSaverProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_freedesktop_screen_saver_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopScreenSaverProxy, g_object_unref)
#endif

void org_freedesktop_screen_saver_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopScreenSaver *org_freedesktop_screen_saver_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopScreenSaver *org_freedesktop_screen_saver_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_freedesktop_screen_saver_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgFreedesktopScreenSaver *org_freedesktop_screen_saver_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgFreedesktopScreenSaver *org_freedesktop_screen_saver_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON (org_freedesktop_screen_saver_skeleton_get_type ())
#define ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON, OrgFreedesktopScreenSaverSkeleton))
#define ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON, OrgFreedesktopScreenSaverSkeletonClass))
#define ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON, OrgFreedesktopScreenSaverSkeletonClass))
#define IS_ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON))
#define IS_ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_FREEDESKTOP_SCREEN_SAVER_SKELETON))

typedef struct _OrgFreedesktopScreenSaverSkeleton OrgFreedesktopScreenSaverSkeleton;
typedef struct _OrgFreedesktopScreenSaverSkeletonClass OrgFreedesktopScreenSaverSkeletonClass;
typedef struct _OrgFreedesktopScreenSaverSkeletonPrivate OrgFreedesktopScreenSaverSkeletonPrivate;

struct _OrgFreedesktopScreenSaverSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgFreedesktopScreenSaverSkeletonPrivate *priv;
};

struct _OrgFreedesktopScreenSaverSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_freedesktop_screen_saver_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgFreedesktopScreenSaverSkeleton, g_object_unref)
#endif

OrgFreedesktopScreenSaver *org_freedesktop_screen_saver_skeleton_new (void);


G_END_DECLS

#endif /* __SRC_SHELL_DBUS_H__ */
